// Auto-generated by export_model_to_c.py for ESP32 / ESP32-S3
// Preprocessing, Quantization, and Wake-Word Detection Constants

#ifndef VAANI_MODEL_CONFIG_H_
#define VAANI_MODEL_CONFIG_H_

// Audio Capture & I2S Specs
#define SAMPLE_RATE_HZ          16000
#define AUDIO_WINDOW_MS         1000   // 1.0 second sliding buffer
#define AUDIO_WINDOW_SAMPLES    16000
#define INFERENCE_HOP_MS        100    // Sliding window shift (100ms)
#define INFERENCE_HOP_SAMPLES   1600
#define COOLDOWN_MS             800    // Debounce cooldown after trigger

// MFCC Feature Extraction Parameters
#define FFT_SIZE                512    // 32 ms frame window
#define FFT_HOP_SIZE            256    // 16 ms frame hop
#define NUM_MEL_BANKS           40
#define NUM_MFCC_COEFFS         13
#define NUM_TIME_FRAMES         63
#define INPUT_TENSOR_SIZE       (63 * 13)

// Tensor Quantization Parameters
#define INPUT_QUANT_SCALE       3.06254601f
#define INPUT_QUANT_ZERO_POINT  68
#define OUTPUT_QUANT_SCALE      0.00390625f
#define OUTPUT_QUANT_ZERO_POINT -128

// Detection & Classification
#define NUM_CLASSES             3
#define CLASS_SILENCE_IDX       0
#define CLASS_UNKNOWN_IDX       1
#define CLASS_VAANI_IDX         2
#define TRIGGER_THRESHOLD       0.60f  // Optimal operational threshold
#define CONSECUTIVE_FRAMES      2      // Multi-window confirmation

#endif  // VAANI_MODEL_CONFIG_H_
