"""
ESP32 Deployment Packager: Converts TFLite Model to C Header Files

Generates:
1. model_data.h   - C byte array (alignas(16)) of the INT8 model for Flash storage
2. model_config.h - Preprocessing constants, quantization scale/zero-point, labels
"""

import sys
from pathlib import Path
import tensorflow as tf

ROOT_DIR = Path(__file__).resolve().parent
MODEL_PATH = ROOT_DIR / "phase5" / "artifacts" / "vaani_v2_int8.tflite"
OUT_DIR = ROOT_DIR / "esp32_deployment"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def main():
    if not MODEL_PATH.exists():
        print(f"Error: Model not found at {MODEL_PATH}", file=sys.stderr)
        sys.exit(1)

    model_bytes = MODEL_PATH.read_bytes()
    model_len = len(model_bytes)

    # Inspect quantization
    interp = tf.lite.Interpreter(model_path=str(MODEL_PATH))
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    out = interp.get_output_details()[0]

    in_scale, in_zp = inp["quantization"]
    out_scale, out_zp = out["quantization"]
    time_frames, n_mfcc = inp["shape"][1], inp["shape"][2]

    # 1. Generate model_data.h
    model_data_h = OUT_DIR / "model_data.h"
    with open(model_data_h, "w") as fp:
        fp.write("// Auto-generated by export_model_to_c.py for ESP32 / ESP32-S3\n")
        fp.write("// Model: Vaani Wake-Word KWS (Tiny DS-CNN Full INT8)\n")
        fp.write(f"// Size: {model_len} bytes ({model_len / 1024:.2f} KB)\n\n")
        fp.write("#ifndef VAANI_MODEL_DATA_H_\n")
        fp.write("#define VAANI_MODEL_DATA_H_\n\n")
        fp.write("#include <stdint.h>\n\n")
        fp.write("// Align to 16 bytes for Xtensa DMA / memory cache\n")
        fp.write("alignas(16) const unsigned char g_vaani_model_data[] = {\n  ")

        for i, b in enumerate(model_bytes):
            fp.write(f"0x{b:02x}, ")
            if (i + 1) % 12 == 0 and i + 1 < model_len:
                fp.write("\n  ")

        fp.write("\n};\n\n")
        fp.write(f"const unsigned int g_vaani_model_data_len = {model_len};\n\n")
        fp.write("#endif  // VAANI_MODEL_DATA_H_\n")

    print(f"[OK] Generated: {model_data_h} ({model_len} bytes)")

    # 2. Generate model_config.h
    model_config_h = OUT_DIR / "model_config.h"
    with open(model_config_h, "w") as fp:
        fp.write("// Auto-generated by export_model_to_c.py for ESP32 / ESP32-S3\n")
        fp.write("// Preprocessing, Quantization, and Wake-Word Detection Constants\n\n")
        fp.write("#ifndef VAANI_MODEL_CONFIG_H_\n")
        fp.write("#define VAANI_MODEL_CONFIG_H_\n\n")
        fp.write("// Audio Capture & I2S Specs\n")
        fp.write("#define SAMPLE_RATE_HZ          16000\n")
        fp.write("#define AUDIO_WINDOW_MS         1000   // 1.0 second sliding buffer\n")
        fp.write("#define AUDIO_WINDOW_SAMPLES    16000\n")
        fp.write("#define INFERENCE_HOP_MS        100    // Sliding window shift (100ms)\n")
        fp.write("#define INFERENCE_HOP_SAMPLES   1600\n")
        fp.write("#define COOLDOWN_MS             800    // Debounce cooldown after trigger\n\n")
        fp.write("// MFCC Feature Extraction Parameters\n")
        fp.write("#define FFT_SIZE                512    // 32 ms frame window\n")
        fp.write("#define FFT_HOP_SIZE            256    // 16 ms frame hop\n")
        fp.write("#define NUM_MEL_BANKS           40\n")
        fp.write(f"#define NUM_MFCC_COEFFS         {n_mfcc}\n")
        fp.write(f"#define NUM_TIME_FRAMES         {time_frames}\n")
        fp.write(f"#define INPUT_TENSOR_SIZE       ({time_frames} * {n_mfcc})\n\n")
        fp.write("// Tensor Quantization Parameters\n")
        fp.write(f"#define INPUT_QUANT_SCALE       {in_scale:.8f}f\n")
        fp.write(f"#define INPUT_QUANT_ZERO_POINT  {in_zp}\n")
        fp.write(f"#define OUTPUT_QUANT_SCALE      {out_scale:.8f}f\n")
        fp.write(f"#define OUTPUT_QUANT_ZERO_POINT {out_zp}\n\n")
        fp.write("// Detection & Classification\n")
        fp.write("#define NUM_CLASSES             3\n")
        fp.write("#define CLASS_SILENCE_IDX       0\n")
        fp.write("#define CLASS_UNKNOWN_IDX       1\n")
        fp.write("#define CLASS_VAANI_IDX         2\n")
        fp.write("#define TRIGGER_THRESHOLD       0.60f  // Optimal operational threshold\n")
        fp.write("#define CONSECUTIVE_FRAMES      2      // Multi-window confirmation\n\n")
        fp.write("#endif  // VAANI_MODEL_CONFIG_H_\n")

    print(f"[OK] Generated: {model_config_h}")


if __name__ == "__main__":
    main()
